[project]
name = "discord-reminder-bot"
version = "1.4.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "black>=25.12.0",
    "dotenv>=0.9.9",
    "feedparser>=6.0.12",
    "py-cord>=2.7.0",
]
