[project]
name = "discord-reminder-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "black>=25.12.0",
    "dotenv>=0.9.9",
    "ipdb>=0.13.13",
    "py-cord>=2.7.0",
    "uvloop>=0.22.1",
]
